"""

Revision ID: 3335ebd88607
Revises: aa8be13a0fa6
Create Date: 2022-09-07 10:50:54.098611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3335ebd88607'
down_revision = 'cff8c2e1030d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_comment_id')
    # ### end Alembic commands ###
